# Generated by Django 3.2.9 on 2023-01-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0010_auto_20221019_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Time', models.TimeField(auto_now=True)),
                ('CNI_number', models.CharField(blank=True, default=' ', max_length=20)),
                ('FirstName', models.CharField(blank=True, max_length=50)),
                ('LastName', models.CharField(blank=True, default=' ', max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50)),
                ('Phone_number', models.CharField(blank=True, default=' ', max_length=100)),
                ('BirthDate', models.DateField(blank=True, default='0000-00-00', null=True)),
                ('Address', models.CharField(blank=True, default=' ', max_length=25)),
                ('Email_address', models.CharField(blank=True, default=' ', max_length=25)),
                ('Role', models.CharField(choices=[('NoRole', 'NoRole'), ('Doctor', 'Doctor'), ('Patient', 'Patient'), ('Receptionist', 'Receptionist'), ('Admin', 'Admin'), ('Accountant', 'Accountant'), ('Nurse', 'Nurse'), ('Labtech', 'Labtech'), ('HRM', 'HRM'), ('Specialist', 'Specialist'), ('Ophtalmologist', 'Ophtalmologist'), ('Pharmacist', 'Pharmacist'), ('Dentist', 'Dentist'), ('Cashier', 'Cashier')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('NoRole', 'NoRole'), ('Doctor', 'Doctor'), ('Patient', 'Patient'), ('Receptionist', 'Receptionist'), ('Admin', 'Admin'), ('Accountant', 'Accountant'), ('Nurse', 'Nurse'), ('Labtech', 'Labtech'), ('HRM', 'HRM'), ('Specialist', 'Specialist'), ('Ophtalmologist', 'Ophtalmologist'), ('Pharmacist', 'Pharmacist'), ('Dentist', 'Dentist'), ('Cashier', 'Cashier')], default='NoRole', max_length=20),
        ),
    ]
